image: node:18

stages:
  - setup
  - test

cache:
  paths:
    - node_modules/

before_script:
  - npm install

setup:
  stage: setup
  script:
    - echo "=== Установка Node.js ==="
    - node --version
    - echo "=== npm version ==="
    - npm --version
  tags:
    - yandex-vm

test:
  stage: test
  script:
    - echo "=== Запуск тестов ==="
    - node test.js
  tags:
    - yandex-vm
  only:
    - master
